name: "Testing"

on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron: "20 1 * * mon"
    workflow_dispatch:

defaults:
    run:
        shell: bash -l {0} # Login shell for conda

jobs:
    unit_tests:
        name: "Unit: ${{ matrix.os }} -- Python ${{ matrix.python-version }}"
        runs-on: "${{ matrix.os }}"

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    # todo(teald): Windows support
                    # - windows-latest

                python-version:
                    - "3.10"
                    - "3.11"
                    - "3.12"

        steps:
            - uses: "actions/checkout@v4"
            - uses: excitedleigh/setup-nox@v2.1.0

            - name: "Install and update pip"
              run: |
                  pip install --upgrade pip poetry nox

            - name: "Unit tests"
              run: nox -s unit_tests --python=${{ matrix.python-version }} -x -- -vv

    integration_tests:
        name: "Integration: ${{ matrix.os }} -- Python ${{ matrix.python-version }}"
        runs-on: "${{ matrix.os }}"

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    # - windows-latest

                python-version:
                    - "3.10"
                    - "3.11"
                    - "3.12"

        steps:
            - uses: "actions/checkout@v4"
            - uses: excitedleigh/setup-nox@v2.0.0

            - name: "Update pip"
              run: |
                  pip install --upgrade pip poetry

            - name: "Integration tests"
              run: nox -s integration_tests -x --python=${{ matrix.python-version }} -- -vv
